### ISSUE TITLE
Getting an error logging in from article, but not homepage.

### ISSUE THREAD

**Issue by coke** [blogs-perl-org/blogs.perl.org#102]
Using chrome. If I go to:

http://blogs.perl.org/

and click on "Sign in", I'm automatically signed in.

But if I (logout and then) go to:

http://blogs.perl.org/users/chen/2010/12/his-most-recent-passion.html

and then click on "sign in", I get the error:

An error occurred

Invalid parameter

**Comment by ap** [comment]
I’m pretty sure I remember making a change to the login script tag at some point, which should have fixed exactly this problem, so I’m closing this. If I’m wrong, please holler.
