### ISSUE TITLE
500 error on posting an entry

### ISSUE THREAD

**Issue by acme** [blogs-perl-org/blogs.perl.org#105]
Thanks for the great website!

However, every single time I post a blog entry, I get a 500 error page when pinging other websites. The post goes up fine, but a 500 error page makes me think it has lost all my wonderful post. This URL gave the 500, if you want to dig through the logs:

http://blogs.perl.org/mt/mt.fcgi?__mode=ping&blog_id=20&entry_id=1403&is_new=1&old_status=0&magic_token=tiya9OfNl4AQkLSKOfs5BB1P0xESuifrrIlodeRJ

**Comment by ap** [comment]
I think pings are disabled systemwide. This ticket is so old I don’t expect a reaction, so I’m closing it – but if this happens to still be a problem, please holler.
