### ISSUE TITLE
RSS feed with entries having a specific tag

### ISSUE THREAD

**Issue by ecocode** [blogs-perl-org/blogs.perl.org#109]
Hi Dave,

Thanks for the wonderful blog site !
I'm writing stuff about perl, but also emacs and finance. As aggregators could be interested in including posts of mine, I'd like to specify a RSS-feed for one or more specific tags.

Currently the RSS for my posts is //blogs.perl.org/users/erik_colson/atom.xml
Is there any way to add a tag-filter for this ?
## Best

erik colson

**Comment by ap** [comment]
You can do this by adding a `Template=feed` parameter to any `mt-search.cgi` URL. E.g. if you click on your `emacs` tag, you are sent to

https://blogs.perl.org/mt/mt-search.cgi?blog_id=531&tag=emacs&limit=20

You can turn this URL into a feed by adding that parameter:

https://blogs.perl.org/mt/mt-search.cgi?blog_id=531&tag=emacs&limit=20&Template=feed

It would be nice if this were advertised I suppose…
