### ISSUE TITLE
Can't configure the Facebook Commenters plugin

### ISSUE THREAD

**Issue by pfig** [blogs-perl-org/blogs.perl.org#115]
When configuring the Facebook Commenters plugin on the blog, I get a "Permission Denied" error message after entering the API key and secret.

It's possible this is set system-wide and individual users can't set their own, in which case the plugin configuration should be disabled (or at the very least some copy telling the user he won't be able to configure it added, and the error message made clearer).

**Comment by ap** [comment]
That plugin stopped working long ago and is not coming back while the site runs MovableType.
