### ISSUE TITLE
merge my openid account?

### ISSUE THREAD

**Issue by schwern** [blogs-perl-org/blogs.perl.org#118]
I have an account on blogs.perl.org using my openid of http://schwern.myopenid.com.  Unfortunately I can't post from that account, so I made one with the username "schwern".

Would it be possible to merge the history from my openid account into my "schwern" account?

Thanks.

**Comment by ap** [comment]
Probably you don’t care any more, but I’ve reattributed the 7 comments you posted under [user ID 296](https://blogs.perl.org/mt/mt-cp.cgi?__mode=view&id=296) to [user ID 1169](https://blogs.perl.org/mt/mt-cp.cgi?__mode=view&id=1169).

The comments are too long ago to show up on your 1169 profile but it’s at least visible that they no longer show up on your 296 profile. They are on the following entries, which I’ve rebuilt so they now reflect the corrected attribution:

* https://blogs.perl.org/users/captain_coconut/2010/07/the-m-word-is-the-wrong-word.html
* https://blogs.perl.org/users/ovid/2010/07/firefoxchromesafari---beautiful-examples-of-objects.html
* https://blogs.perl.org/users/rurban/2011/01/why-modulebuild-sucks.html
* https://blogs.perl.org/users/ovid/2010/01/roles-without-moose.html
* https://blogs.perl.org/users/sawyer_x/2011/03/dancer-release-codename-the-schwern-cometh.html
