### ISSUE TITLE
Error when submitting a comment

### ISSUE THREAD

**Issue by autarch** [blogs-perl-org/blogs.perl.org#119]
I'm logged in with OpenID, and trying to submit a comment on http://blogs.perl.org/users/steven_haryanto/2011/02/the-coming-bloated-perl-apps.html

I keep getting this error:

```
Can't call method "remove" on an undefined value 
```

That's all I've got for you, I'm afraid.

**Comment by ap** [comment]
I’m pretty sure this bug is still present, but its relevance has become theoretical since b.p.o only supports legacy OpenID, which is largely dead, and I’m afraid this is not changing anytime soon.
