### ISSUE TITLE
“Your session has expired” if you preview a comment then submit

### ISSUE THREAD

**Issue by neilb** [blogs-perl-org/blogs.perl.org#196]
I might have found the cause of my previous issue.

I just wrote a comment on Berekuk's play-perl post. After reading his post, I logged in, then went to the comment box. I hit preview, and when happy, I hit submit. I got the following:

![Screen Shot 2013-04-04 at 23 57 49](https://f.cloud.github.com/assets/478461/341755/8d1df648-9d7b-11e2-9f29-7a138e908578.png)

Maybe this is what I got last time, but didn't notice as I moved on to the next thing. I went back in the browser, copied the text, went to the home page, clicked on the article again, pasted the content and did submit without review, and everything worked fine.

**Comment by ap** [comment]
This is now fixed.

**Comment by shlomif** [comment]
On Sat, 08 May 2021 19:14:20 -0700
Aristotle Pagaltzis ***@***.***> wrote:

> This is now fixed.
> 

Regards,

	Shlomi Fish

-- 

Shlomi Fish       https://www.shlomifish.org/
https://www.shlomifish.org/humour/bits/facts/Emma-Watson/

After Chuck Norris said “I don’t believe in fairies.”, fairies have become
extinct.
    — https://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - https://shlom.in/reply .
