### ISSUE TITLE
Request-URI Too Large

### ISSUE THREAD

**Issue by ghost** [blogs-perl-org/blogs.perl.org#204]
After submitting a search I get the following error when attempting to view page 2 and subsequent pages:

Request-URI Too Large

The requested URL's length exceeds the capacity limit for this server.
Apache/2.2.12 (Ubuntu) Server at 188.40.132.3 Port 80

**Comment by ap** [comment]
If there isn’t a good way, let’s go with a bad way. Maybe it’s even not; I don’t understand the MT codebase well enough to judge my fix. Probably it is a kludge but it might conceivably be a reasonable one, I can’t say. It works for front page searches in any case, including tag searches, which is good enough for me, particularly if I haven’t broken anything else in the process.
