### ISSUE TITLE
your session expired, without preview

### ISSUE THREAD

**Issue by vsespb** [blogs-perl-org/blogs.perl.org#222]
I've just was tried to post something, and got "your session is expired". I reloaded page - same result. I was logged in. I logged out and re-login. After that posting was successful.

And I did not use "post preview".

my login on forum: `vsespb`

related: #215

**Comment by awake416** [comment]
Same here, I logged in and within a minute, i wrote the content in comment box, then preview and it submit, it says session expired. Same thing when i do after clicking back button worked.

**Comment by ap** [comment]
This is a duplicate of #196, [which I fixed a while ago](/blogs-perl-org/blogs.perl.org/issues/196#issuecomment-835631396).
