### ISSUE TITLE
Comment posts always blocked

### ISSUE THREAD

**Issue by barbie** [blogs-perl-org/blogs.perl.org#223]
Over the past month, I have tried to comment on a couple of posts. However, I am now always blocked and comments are held for approval by the blog owner. Except they never get approved. Others post with no issue. This happens for both my own login (Barbie) and the CPAN Testers login.

I can make blog posts from both, but am blocked from commenting. Have just commented on Leon's recent post, if you need to see an example (2013-08-09 08:44:00 approx). This was posted via my Babrie login. 

Please delete the recent comment post from the CPAN Testers login, as they are not appropriate now.

**Comment by ap** [comment]
There aren’t any recent pending or spam-trapped comments. That isn’t proof positive that this issue is resolved but the whole comment spam and anti-spam landscape looks very different in 2022 anyway.
