### ISSUE TITLE
Top menubar rendering issue

### ISSUE THREAD

**Issue by tm604** [blogs-perl-org/blogs.perl.org#233]
When logged in, the text in the menu bar at the top shifts down:

![image](https://f.cloud.github.com/assets/2883904/1443196/cb673852-41da-11e3-8697-80e2d5c24db4.png)

Name too long perhaps?

cheers,

Tom

**Comment by ap** [comment]
I believe this is fixed. If not, please holler.

**Comment by ronsavage** [comment]
Hi

Looks good to me now. Thanx.

---
Cheers
Ron
savage.net.au
