### ISSUE TITLE
Google OpenID login not possible

### ISSUE THREAD

**Issue by Sadrak** [blogs-perl-org/blogs.perl.org#258]
i tried to login with the following URL:
- https://www.google.com/accounts/o8/id

I get the following error: 
- An error occurred
- Can't call method "name" without a package or object reference

**Comment by daveola** [comment]
It seems that *any* OpenID login is broken on blogs.perl.org, not just google.

Disappointing.

**Comment by imran-uk** [comment]
I tried to sign-in using my Google account today, got the following error:

`Could not verify the OpenID provided: The address entered does not appear to be an OpenID`

**Comment by ap** [comment]
b.p.o only supports legacy OpenID, which is largely dead. I’m afraid this is not changing anytime soon.
