### ISSUE TITLE
Google Login not possible

### ISSUE THREAD

**Issue by bulk88** [blogs-perl-org/blogs.perl.org#267]
![badperlblogs google](https://cloud.githubusercontent.com/assets/997168/2692771/4b3d97ca-c3a8-11e3-98f5-e5c1c9f74be6.PNG)

**Comment by agrinevich** [comment]
I have the same issue. Can't sign in using Google.

**Comment by ap** [comment]
b.p.o only supports legacy OpenID, which is largely dead. I’m afraid this is not changing anytime soon.
