### ISSUE TITLE
»Search this blog«

### ISSUE THREAD

**Issue by daxim** [blogs-perl-org/blogs.perl.org#28]
In the screenshot http://www2.pic-upload.de/11.12.09/cuji68t225hx.png pay attention to the elements marked with number 3.

What does this mean exactly? I guess here it means »Search all blog entries by davorg«. If this is true, change it to »Search all blog entries by `<a href="http://blogs.perl.org/users/dave_cross/">davorg</a>`«

**Comment by ap** [comment]
Unfortunately any of the suggested alternatives to the label would not be entirely accurate. I’ve turned it into `Search <a href="http://blogs.perl.org/users/aristotle/">this blog</a>`. Hopefully this is enough of a hint about what “this blog” is supposed to mean.

(For now this is only visible on my own blog. To percolate to the rest of the site I’d need to run a full site rebuild, which I’m going to hold off on until more changes accumulate. But it will show up eventually.)
