### ISSUE TITLE
Can't change password (no confirmation email field)

### ISSUE THREAD

**Issue by osfameron** [blogs-perl-org/blogs.perl.org#285]
To try to change password I:

 # click on "Edit profile" link and get to http://blogs.perl.org/mt/mt-cp.fcgi?__mode=edit
 # type new password, and confirm it

I get an error with "Failed to verify current password."

There is no field to verify the current password.

(I've tried entering current password into the "Confirm password" field, in case it was mislabelled).

**Comment by ap** [comment]
Fixed! Sorry it took this long.
