### ISSUE TITLE
Getting 'An error occurred: Permission denied. ' error

### ISSUE THREAD

**Issue by perlancar** [blogs-perl-org/blogs.perl.org#292]
I'm getting error message 'Getting 'An error occurred: Permission denied. ' when trying to post a comment here: http://blogs.perl.org/users/luca_ferrari/2014/12/about-one-liners.html and wonder what that error is about (spam protection? another reason?). Perhaps more details can be given in the error message.

**Comment by ap** [comment]
Yes, so it is. So I’m closing this one.
