### ISSUE TITLE
Can't register with MT, can't post blogs

### ISSUE THREAD

**Issue by davehodg** [blogs-perl-org/blogs.perl.org#293]
Hi,

The CPAN PR challenge folks would like to blog our efforts. Can we register and post please?

Ta,

Dave

**Comment by ap** [comment]
Hi @davehodg, sorry about that. We had a security-related situation recently and our only defence for the time being was to shut out new registrants. We are deeply unhappy with the situation as manpower for dealing with issues on the site is always extremely limited. I had hoped we could keep the downtime short, but it has dragged on for weeks. I hope we’ll have better news for you sometime soon.

**Comment by davehodg** [comment]
We've got around 200 people working on the pr-challenge, excellent publicity for perl, is there anything we can do to help?

Have you filed a concern with moveabletype.com?

**Comment by xsawyerx** [comment]
@ap is it possible to prepare a csv and import it into the system by an admin? We can prepare a list of valid users who want to register, along with all the registration information needed.

@davehodg 200 is not accurate. Some have an account, some have others blogs, some aren't interested in blogging. We don't know what the list size will be yet. I'll be ecstatic if it's over 20.

**Comment by labrown** [comment]
I'd like to be able to blog about my CPAN Pull Request Challenge on blogs.perl org, please. :-)

**Comment by karenetheridge** [comment]
I'm not a new user but I also have not been able to log in or post for the last few days either --  all attempts to log in were met with "permission denied" responses, and after I forcibly changed my password (via the "forgot my password" route), I was able to log in but attempts to post were then met with "permission denied".
(My userid is "Ether".)

**Comment by ap** [comment]
@karenetheridge: that’s a whole other bug: see #291. We have plenty of bugs to go around for everyone!

@xsawyerx: if it’s two dozen users, just gimme the emails and names and usernames and I’ll register them by hand. I think that’s the most expedient option.

**Comment by neilbowers** [comment]
Thanks @ap -- I'll try and coordinate to get you a list of users!

**Comment by djzort** [comment]
i seem to get 'Permission Denied' for my djzort user

**Comment by Camspi** [comment]
@ap: I sent you an email requesting an account. :)  Let me know if it failed to find its way to you.

**Comment by elcamlost** [comment]
Now is May 18 and registration is still close. More over, google authentication is broken too.
Is it possible to fix this?

**Comment by umbrait** [comment]
Any chance to get an account to post some YAPC related stuff?

**Comment by neilbowers** [comment]
@umbrait can you email me your preferred username, name and email address please, and I'll ask someone to add an account for you. My email is neil at bowers dot com.

**Comment by labrown** [comment]
It's fixed!!!!  I just registered an account on blogs.perl.org and it looks like I can even post!  Woohoo.

**Comment by karenetheridge** [comment]
Still no luck for me -- I get "Invalid login." when attempting to sign in.

**Comment by djzort** [comment]
@karenetheridge try this link? http://blogs.perl.org/mt/mt.fcgi 

see also https://github.com/blogs-perl-org/blogs.perl.org/issues/294

**Comment by ap** [comment]
@karenetheridge seems [happily signed up since](https://blogs.perl.org/mt/mt-cp.cgi?__mode=view&id=836).

Signup has been re-enabled for years so I’m closing this. If anyone has problems signing up independently of that situation, please holler.
