### ISSUE TITLE
Access Denied for my blogs.perl.org user?

### ISSUE THREAD

**Issue by djzort** [blogs-perl-org/blogs.perl.org#294]
I seem to be getting 'access denied' when i enter my correct log in credentials.

Username 'djzort'

Please help?

**Comment by ap** [comment]
Does it actually say “access denied” or is this a duplicate of #291?

**Comment by djzort** [comment]
AFAIK its different

**Comment by djzort** [comment]
ping?

**Comment by lajandy** [comment]
Ok, I don't know whether my problem is this or #291 but I cannot login either.  I can recover my password, but nothing I set my password to will work in the login page.  And just like in #291, when I recover my password, I seem to be logged in but I cannot post any comments.

**Comment by djzort** [comment]
When i do a password reset, i am logged in and can post. If i log out and (try) to log in again - but get Access Denied.

When i am logged in (having reset password) - if i try to post a comment i get "An error occurred: Permission denied. "

**Comment by asb-capfan** [comment]
Same here, username is capfan.

**Comment by djzort** [comment]
perhaps @arc or @davorg can help?

**Comment by davorg** [comment]
I've spent some time looking into this issue and I really don't know what's going on. And I'm well beyond the limits of my MT knowledge. If there's anything I can do to help people investigate this issue, then please let me know. But currently I have no idea what my next steps would be.

**Comment by djzort** [comment]
At the risk of stating the obvious...
a) anything in logs?
b) turn on query logging and see what its looking at in the db?

**Comment by djzort** [comment]
:(

**Comment by djzort** [comment]
when i log in via password reset, if i go to make a comment on a post i also get "An error occurred: Permission denied. "

**Comment by sjn** [comment]
I can confirm this bug also affects me.

**Comment by jsober** [comment]
This is also affecting me. Additionally, the google login plugin is outdated and does not work anymore.

**Comment by tartansandal** [comment]
I'm getting the "Permission denied" error too. If I do the "forgot password" dance once or twice I can get back in.  Username is 'kal' if that helps.  Can help with debugging this if you need it.

**Comment by tartansandal** [comment]
Just noticed, there seems to be two login forms with subtly different layout. One of them works.  If this is being load balanced, perhaps one copy is running a different version.

**Comment by djzort** [comment]
what are the two different forms? are they different uri or are you seeing different forms on the same uri

**Comment by tartansandal** [comment]
I was not aware of any change in the URL, but there might have been.
Just checking now: http://blogs.perl.org/mt/mt-cp.fcgi gives me the bad form.

![selection_063](https://cloud.githubusercontent.com/assets/3327775/8174624/4ba1b3e2-1422-11e5-8e07-69f20eee2608.png)


From memory, the good one has the sign in button on the right.
The bad form has the sign in button on the left.

**Comment by djzort** [comment]
This is the link with the button on the RHS - http://blogs.perl.org/mt/mt.fcgi

It works for me also

**Comment by tartansandal** [comment]
Awesome. Just checked and that link works for me too. Now we just need to figure out where the other link is coming from.

**Comment by djzort** [comment]
Its in http://blogs.perl.org/mt.js

**Comment by djzort** [comment]
perhaps the upgrade wasn't performed correctly?

**Comment by djzort** [comment]
Can someone look into this now that the "problem" seems to be identified?

**Comment by wbraswell** [comment]
Thank goodness at least we figured out a link that works, this is a really bad bug which needs to be fixed!

**Comment by djzort** [comment]
somehow logging in now all works for me as does commenting. closing this ticket.
