### ISSUE TITLE
Logging in with Google no longer works

### ISSUE THREAD

**Issue by jjn1056** [blogs-perl-org/blogs.perl.org#297]
Looks like the google ID login doesn't work anymore and I can't seem to comment with any sort of account :(

**Comment by vividsnow** [comment]
same thing, cant login/comment

p.s. migration from google openid to googe oauth2 requires some quirks: 
https://stackoverflow.com/questions/29726093/google-openidconnect-why-am-i-not-getting-an-openid-id-value-along-with-sub/29732052#29732052

**Comment by djzort** [comment]
see also https://github.com/blogs-perl-org/blogs.perl.org/issues/294

**Comment by vogelke** [comment]
Same here, I can login but when I try to submit a comment, I keep getting the message "Your session has expired, please login again."

**Comment by djzort** [comment]
works for me now, hence i closed off #294

**Comment by jrw** [comment]
Still getting sporadic "Your session has expired..." after logging in and trying to submit a comment (Firefox).  But after trying another browser and getting the same error, I tried again on Firefox and it worked.

**Comment by tmetro** [comment]
> Still getting sporadic "Your session has expired..." 

Likewise, when trying to reply to:
http://blogs.perl.org/users/buddy_burden/2020/01/a-date-with-cpan-update-3-golden-jubilee.html#comment-1809716

using Chrome. Switched to Firefox, and it worked. Ironically my Firefox config is far more restrictive of JS and cookies.

**Comment by ap** [comment]
b.p.o only supports legacy OpenID, which is largely dead. I’m afraid this is not changing anytime soon.
