### ISSUE TITLE
crud in the input field

### ISSUE THREAD

**Issue by daxim** [blogs-perl-org/blogs.perl.org#30]
In the screenshot http://www2.pic-upload.de/11.12.09/cuji68t225hx.png pay attention to the elements marked with number 5.

If I want to do a search with the built-in site search, I have to first delete the useless crud that is prefilled in the input form element. Remove the crud. Make the element descriptive by associating it with a label instead, see http://www.w3.org/TR/html4/interact/forms.html#h-17.9.

**Comment by ap** [comment]
Fixed by converting it to a `placeholder`. In 2009 this would have required more effort to fix.
