### ISSUE TITLE
Two openId (?) spam comments

### ISSUE THREAD

**Issue by Corion** [blogs-perl-org/blogs.perl.org#304]
http://blogs.perl.org/users/jt_smith/2015/12/christmas-came-bah-humbug.html#comment-1649172

links the "user" to 

    http://bingung.my.id/

which looks spammy. The same goes for

http://blogs.perl.org/users/ron_savage/2016/01/article-installation-of-imagemagick-under-debian.html#comment-1649506

which points to

    http://www.b3lok.com/

... which looks equally spammy.

**Comment by arc** [comment]
Thanks as ever, Max — I've zapped those now.
