### ISSUE TITLE
My Bad :) 

### ISSUE THREAD

**Issue by ThisUsedToBeAnEmail** [blogs-perl-org/blogs.perl.org#306]
Not Found

The requested URL /users/robert_acock/2016/01/social-media-meta-tags.html was not found on this server.

I made a mistake thinking I could edit my post, but instead it posted twice... So I deleted my first post... and I think that is what has caused this.

**Comment by ThisUsedToBeAnEmail** [comment]
cheers dude

**Comment by davorg** [comment]
I republished the entry and that seemed to fix it.

**Comment by ThisUsedToBeAnEmail** [comment]
Can I add my plugin to the blog....
