### ISSUE TITLE
date/time stamp

### ISSUE THREAD

**Issue by daxim** [blogs-perl-org/blogs.perl.org#31]
In the screenshot http://www2.pic-upload.de/11.12.09/cuji68t225hx.png pay attention to the elements marked with number 6.

Use a 24 hour time stamp by default. Identify the time zone of the time stamp.

Tool tip for the stamp is literally »iso8601«. This is a useless title attribute. Change the markup according to http://microformats.org/wiki/datetime-design-pattern.

**Comment by ap** [comment]
Converted to [`<time>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time).

(Won’t show up everywhere until a full site rebuild, which I’m going to hold off on until more changes accumulate.)
