### ISSUE TITLE
SEO BLAKE is a spammer

### ISSUE THREAD

**Issue by Corion** [blogs-perl-org/blogs.perl.org#311]
`http://blogs.perl.org/users/seo_blake/`
`http://blogs.perl.org/mt/mt-cp.fcgi?__mode=view&id=4218`
`http://blogs.perl.org/users/seo_blake/nagaqqcom-agen-bandarq-bandarq-online-aduq-online-dominoqq-terbaik.html`

**Comment by arc** [comment]
Nuked. Thanks as always!
