### ISSUE TITLE
Article tagged with '<pre>' messes up Atom feed

### ISSUE THREAD

**Issue by dakkar** [blogs-perl-org/blogs.perl.org#313]
The article at http://blogs.perl.org/users/quepadretanpadre/2016/08/quepadre.html has a tag of `<pre>` (yes, with the angle brackets). This confuses both the HTML renderer (which strips it) and the Atom renderer (which produces `<category term="pre" label="<![CDATA[<pre>]]>"`).
Could someone remove that tag from the post?
Thanks!

**Comment by davorg** [comment]
Done. Thanks for the report.
