### ISSUE TITLE
»Comment Submission Error«

### ISSUE THREAD

**Issue by daxim** [blogs-perl-org/blogs.perl.org#32]
See screenshot http://www2.pic-upload.de/11.12.09/gg7ag4614xk5.png.

No matter what I do, I can't preview or submit a commit. The error message is »Your comment submission failed for the following reasons: Invalid request«, which is rubbish because it does not tell me what exactly it thinks is invalid.

**Comment by ap** [comment]
This looks like a mix of problems from before multiple fixes. I am by no means confident that all of them are resolved but I really can’t tell which ones are (possibly all, possibly none). So while I really don’t like doing this, I’m going to close this and hope any of these that are still an issue are filed again.
