### ISSUE TITLE
Can't create entries

### ISSUE THREAD

**Issue by nkh** [blogs-perl-org/blogs.perl.org#321]
user name: nkh

I am automatically signed in when I open the page, saved the password in the browser. 

if I want to create a log entry, I get to a moveable type page that asks for a password, I get multiple error message from there.  the latest being "unknown User".

I have tried multiple time to reset the password.

I don't mind the account being removed, I can create a new one but I'd like to keep my user name.

**Comment by davorg** [comment]
Your user was still pending validation. I guess there was a problem sending the validation email to you. I've validated your user manually, so it should now work (well, about as well as MT ever works).

Let me know how it goes so I can (hopefully) close this ticket.

**Comment by nkh** [comment]
I get a bit further but I haven't tried to  add a post yet. But I tried to comment on a recent post and I get "An error occurred: Permission denied." although the text "Thanks for signing in, Nadim Khemir. (sign out) " is displayed above the comment field.

**Comment by davorg** [comment]
Looks like you got in and managed to post. Sorry for the horrible state of the site. We're hoping to replace it with something new very soon. Until then we're all just going to have to deal with these problems :-/

**Comment by nkh** [comment]
With you help, and some insistence, I did manage.

Thank you again :)
