### ISSUE TITLE
Comment SPAM

### ISSUE THREAD

**Issue by MartinMcGrath** [blogs-perl-org/blogs.perl.org#330]
Comment SPAM linking to https://www.milesweb.com:

http://blogs.perl.org/users/buddy_burden/2017/02/of-dates-and-sigs-and-shiny-things-and-cabbages-and-kings.html#comments

http://blogs.perl.org/users/sergey_kolychev/2017/02/machine-learning-in-perl.html#comment-1784363

**Comment by davorg** [comment]
Thanks. I've deleted those comments and banned the commenter.
