### ISSUE TITLE
Password recovery

### ISSUE THREAD

**Issue by rlauer6** [blogs-perl-org/blogs.perl.org#333]
Not working...never sends email

**Comment by arc** [comment]
Hi, Robert. I'm sorry this isn't working for you.

I can see lines in the mail server log that apparently indicate your ISP is accepting the password-reset messages from our system, so perhaps they've been delivered to a spam folder or similar?

If not, then please confirm your blogs.perl.org username, and I'll see if I can find another way to make this work.

Thanks.

**Comment by rlauer6** [comment]
Thanks.  I have my comcast mail forwarded to gmail and for some reason
those emails did not get forwarded at 9am, but I just tried again and it
was forwarded - odd.  I do appreciate you checking the logs for me since
that pointed me to looking at comcast directly.


Thanks

Rob

**Comment by arc** [comment]
No problem — I'm glad it's working now 😄
