### ISSUE TITLE
No PNG support?

### ISSUE THREAD

**Issue by oylenshpeegul** [blogs-perl-org/blogs.perl.org#34]
I uploaded a PNG for a userpic and it just showed a black square. I uploaded a GIF instead and that worked.

**Comment by benkasminbullock** [comment]
I have a PNG for a userpic:

http://blogs.perl.org/mt/mt-static/support/assets_c/userpics/userpic-648-100x100.png

So I think this issue may be resolved now.

**Comment by ap** [comment]
Looks like it.
