### ISSUE TITLE
http://blogs.perl.org/users/vietnam/ is a spammer

### ISSUE THREAD

**Issue by Corion** [blogs-perl-org/blogs.perl.org#341]
`http://blogs.perl.org/users/vietnam/`

reposted 

http://blogs.perl.org/users/dean/2017/06/new-sydney-pm-website-and-url.html

but with their URL in the profile

**Comment by ap** [comment]
If it weren’t in bad taste, I’d make a joke here about how I’ve nuked Vietnam.

Thanks for the report.
