### ISSUE TITLE
Get RSS for a given tag

### ISSUE THREAD

**Issue by amba** [blogs-perl-org/blogs.perl.org#343]
Hi,
is there a way to get a RSS feed for all articles with a given tag? E.g. all articles in 
http://blogs.perl.org/mt/mt-search.fcgi?blog_id=2858&tag=lab-measurement&limit=20

thanks

**Comment by ap** [comment]
You can add a `Template=feed` query parameter to a search to get its output as a news feed, i.e. (for your example)

http://blogs.perl.org/mt/mt-search.fcgi?blog_id=2858&tag=lab-measurement&limit=20&Template=feed
