### ISSUE TITLE
Cannot change password

### ISSUE THREAD

**Issue by jrw** [blogs-perl-org/blogs.perl.org#348]
Trying to change my password I go to Edit Profile and get to an insecure page(!) where I can enter my new password.  Pressing Save takes me to a page blogs.perl.org/mt/mt-cp.fcgi which says "Failed to verify current password."  But it never asked me to verify my current password.  Also, why is the page where I enter my new password not https?  Tried this in latest Firefox and Chromium, both on Linux.

**Comment by arc** [comment]
I've just tried this in Chrome, and it's working for me. The only thing I can think of off the top of my head is that maybe you have JavaScript disabled? The "Edit Profile" page has a JavaScript-driven "Change password" link, and when I click that it's replaced with these fields:

![image](https://user-images.githubusercontent.com/23287/39524981-9f206374-4e12-11e8-9681-6ab06efe4345.png)

I can enter my current password and two copies of a new password, and then "Save changes" works.

(The lack of https is essentially historical at this point, but changing it would require time, in quantities that the current admins don't have available.)

**Comment by jrw** [comment]
Yes, I have a JavaScript blocker, but it's disabled for ...perl.org, and the page I end up on doesn't have any JavaScript on it that's being blocked.  Even when I globally disable my blocker, I still don't see what you see.  There's no "Change password" link.

Here's what I do:  log into blogs.perl.org, click Edit Profile at top right, end up on http://blogs.perl.org/mt/mt-cp.fcgi?__mode=edit&blog_id=1&return_to=http%3A%2F%2Fblogs.perl.org%2F

Here's what I see:

**Comment by ap** [comment]
Go to http://blogs.perl.org/mt/mt.fcgi and log in there. It will say “Hi jrw” (or whatever your username is) at the top right. If you click on that, you will get the screen that @arc mentioned.

**Comment by ap** [comment]
Fixed! Sorry it took this long.

**Comment by jrw** [comment]
Thanks, Aristotle!  It works now.
