### ISSUE TITLE
Continually forgets password 

### ISSUE THREAD

**Issue by rlauer6** [blogs-perl-org/blogs.perl.org#352]
Every time I try to create a new post, despite that fact that I am logged in, it asks me to login.  When I do, it claims my password is incorrect.  I then reset the password and it then lets me in to post.  What am I doing wrong here? It's a frustrating experience.

**Comment by davorg** [comment]
It's not that you're doing anything wrong. It's that the software running the site is fundamentally broken in many ways. We are working on a replacement system and hope to have news about that before long.

Sorry for the inconvenience.

**Comment by rlauer6** [comment]
Thanks - I feel better knowing I'm not missing something obvious and look forward to the new blogging engine.
