### ISSUE TITLE
blogs.perl.org content is mirrored

### ISSUE THREAD

**Issue by perlpunk** [blogs-perl-org/blogs.perl.org#353]
I just found this site: `https://hk.saowen.com/source/site/blogs_perl_org`
It mirrors all articles, but leaves out author names. I guess this is not authorized.

The reason why I found it is actually that I did a search on duckduckgo.com for "strings in yaml quote".
https://duckduckgo.com/?q=strings+in+yaml+quote&t=hl&ia=web
I can find my article on YAML on the mirror site in the search results, but not blogs.perl.org.
Contrary to that, searching for "strings yaml" on Google finds blogs.perl.org first.

Edit: see also https://nickmchardy.com/2018/12/the-day-i-found-saowen.com-had-stolen-my-content.html (thanks @HaraldJoerg for the link)

**Comment by ap** [comment]
That whole site is 403 now so I guess the problem resolved itself…
