### ISSUE TITLE
User "Sharad" is a spammer

### ISSUE THREAD

**Issue by Corion** [blogs-perl-org/blogs.perl.org#355]
The (shortened) link goes to their "interview questions" spam site. I don't think that stuff is appropriate for blogs.perl.org

    http://blogs.perl.org/users/sharad/
    http://blogs.perl.org/users/sharad/2019/03/perl-interview-questions.html

Thanks!

**Comment by arc** [comment]
Nuked — thanks!

**Comment by davorg** [comment]
I wondered about that one. I mean, it's obviously spam. But could we have had more effect by just writing loads of comments pointing out the problems with the article :-)
