### ISSUE TITLE
Possible spam

### ISSUE THREAD

**Issue by choroba** [blogs-perl-org/blogs.perl.org#356]
There's a comment by "Shivkumar" [here](http://blogs.perl.org/users/stephan_loyd/2019/03/data-analysis-and-visualization-in-perl.html#comment-1807277). The user isn't registered at blogs.perl.org. Their name links to a commercial page.

This is a borderline thing. Their comment is vacuous, but I'm not sure it should be deleted. Is it possible just to remove the link from their name?

**Comment by davorg** [comment]
Good suggestion. Done.

**Comment by ap** [comment]
It looks borderline if you haven’t seen that sort of comment 100,000 times, but it’s really just standard comment spam filler text. There’s two main kinds, either ultra-generic praise like this, or ultra-generic “problem” reports à la “I have a problem with your CSS”. Always coupled with a spammy link.

They’re never worth keeping. There’s no actual person who thought what the comment said, and wanted to say it.

I’ve nuked the comment outright.
