### ISSUE TITLE
User "jonathan2" is a spammer

### ISSUE THREAD

**Issue by Corion** [blogs-perl-org/blogs.perl.org#360]
It's surprisingly well written high-quality spam, but it's still spam, linking for a cheap game token site:

    `http://blogs.perl.org/users/jonathan2/2019/07/marvel-future-fight-turns-one-year-old-this-month.html`
    `http://blogs.perl.org/users/jonathan2/`

**Comment by davorg** [comment]
Thanks. Nuked.
