### ISSUE TITLE
Cannot comment on a post

### ISSUE THREAD

**Issue by matthewpersico** [blogs-perl-org/blogs.perl.org#375]
http://blogs.perl.org/users/quickman/2019/11/some-useful-functions-for-financial-calculations-part-1.html#comments doesn't bring up a box to post comments. I am signed in. Please advise.

**Comment by arc** [comment]
The poster has disabled the ability for people to comment on that post. Sorry.

**Comment by matthewpersico** [comment]
The poster is a moron. I was going to point him to https://metacpan.org/pod/Finance::Performance::Calc to either save him some time or give him some ideas. SMH.
