### ISSUE TITLE
Please remove old site

### ISSUE THREAD

**Issue by thomassoldan** [blogs-perl-org/blogs.perl.org#383]
This site links to my former employer, so I'd like to remove it ASAP. 

They claim to have lost the login that established it. 

Thank you. 

http://blogs.perl.org/users/thomas_soldan/

**Comment by ap** [comment]
It’s astonishing how many attorneys employ SEO spammers. Did that come back to bite you now? Is Google on to you and hurting your new site? That’s the best case scenario I can imagine here. My sympathies for your plight are beyond limited. Count yourself lucky that I have been on a mission to wipe all SEO spam off the site, which you get to benefit from.

**Comment by thomassoldan** [comment]
Actually I believe it was an unauthorized scrapper. But I am grateful for
your help, my old firm claimed to have no knowledge.
