### ISSUE TITLE
No where to get help?

### ISSUE THREAD

**Issue by LadyAleena** [blogs-perl-org/blogs.perl.org#385]
There is no where on the site where one can click to get help that I can find. It took me several minutes to find this repository to report this. So, please provide a helpful link to where users can get help when needed, even if the link is to the issues page in this repository.

**Comment by ap** [comment]
Take another look. Does this help?

**Comment by ap** [comment]
Take another look now. Does this help?

**Comment by LadyAleena** [comment]
It's okay.
