### ISSUE TITLE
Top links jump out box when viewing blog entries

### ISSUE THREAD

**Issue by LadyAleena** [blogs-perl-org/blogs.perl.org#386]
When viewing the main page of the site, I see this at the top.
![Screenshot_bpo_1](https://user-images.githubusercontent.com/123256/92046446-8dc6bd00-ed50-11ea-937d-6bb0703afa1d.png)
When I go to view an individual blog entry, I see this at the top.
![Screenshot_bpo_2](https://user-images.githubusercontent.com/123256/92046447-8e5f5380-ed50-11ea-898d-5614de8aad7f.png)
The links are hard to read when not in the box.

**Comment by ap** [comment]
Fixed now?

**Comment by LadyAleena** [comment]
Looks like it. Thanks!
