### ISSUE TITLE
Comment preview does not submit

### ISSUE THREAD

**Issue by LadyAleena** [blogs-perl-org/blogs.perl.org#387]
I wrote a comment reply and previewed it. After previewing, I hit submit, then left the site. I came back to find the reply did not go through. I made two previous comment replies and submitted them without using preview, and they are up. Now I can't remember what that lost reply was.

**Comment by ap** [comment]
Did you not get an error after submitting from the preview screen? (That would be a known issue, #196 )

**Comment by LadyAleena** [comment]
No, I did not. There were no error messages. I thought the comment was submitted and all was well.

**Comment by smonff** [comment]
I experience quite the same. Tried to comment to times today and it got refused.

Some time ago I did all kind of complicated manipulations like unlogging and re-logging and finally at some point it got posted, eventually.

**Comment by smonff** [comment]
Ok, I did what[ is recommended](https://github.com/blogs-perl-org/blogs.perl.org/issues/196#issuecomment-18390803) in #196 and it is it.

**Comment by smonff** [comment]
> Ok, I did what[ is recommended](https://github.com/blogs-perl-org/blogs.perl.org/issues/196#issuecomment-18390803) in #196 and it is it.

Except the difference was that I was having a cat on my lap...

**Comment by ap** [comment]
@LadyAleena Has this happened to you again since?

**Comment by LadyAleena** [comment]
I have not been to the site in some time. I do not know if this is still an ongoing issue.

**Comment by ap** [comment]
OK. Thanks for responding.
