### ISSUE TITLE
PLEASE DELETE SPAM USER IMMEDIATELY!

### ISSUE THREAD

**Issue by wbraswell** [blogs-perl-org/blogs.perl.org#388]
As of today, the top story on BPO is a spam post about Mumbai real estate sales.

Please delete and ban the spammer ASAP!

http://blogs.perl.org/users/group_integrated/flats-for-sale-in-mulund-west.html

**Comment by ap** [comment]
Check your Caps Lock button? 🙂

**Comment by wbraswell** [comment]
@ap 
Wow thanks for the quick turn-around!  :+1: 
The only reason I used all caps is because I honestly was not sure if this GitHub repository was being regularly monitored or maintained.

**Comment by ap** [comment]
🙂 Not only is the issue tracker monitored, so is the site – I get a notification whenever a user publishes their first entry, and I’d already caught this one by the time you made the ticket.

(There is quite a lot more spam than what people report here – roughly an entry every couple of days. Plus there are accounts created just to put spammy links in the profile’s bio, which are basically invisible to regular readers of the site. I’m keeping an eye on all of it, though I’m not always at my desk to nuke it right away. The trash is being taken out regularly.)

**Comment by wbraswell** [comment]
That is awesome, thank you so much for your ongoing behind-the-scenes work to keep spam off BPO!
