### ISSUE TITLE
Spammer -  Maketrip USA

### ISSUE THREAD

**Issue by MartinMcGrath** [blogs-perl-org/blogs.perl.org#396]
http://blogs.perl.org/users/jackfitt/2020/11/who-takes-purpose-at-cervical-most-cancers-to-reduce-cases-deaths.html#comments

**Comment by ap** [comment]
Nuked, thanks.

**Comment by MartinMcGrath** [comment]
@ap see also http://blogs.perl.org/users/c_y_fung/2020/11/cys-take-on-pwc087.html#comments http://blogs.perl.org/users/alex1/2020/11/where-is-rob.html#comments

**Comment by ap** [comment]
Yeah, I saw them a few hours after I nuked the account. There aren’t just those, there were a whole bunch across a number of posts.

But not any more. 🙂
