### ISSUE TITLE
Add SSL to the site.

### ISSUE THREAD

**Issue by matthewpersico** [blogs-perl-org/blogs.perl.org#410]
Is it really as easy as http://blogs.perl.org/users/nerdvana/2021/11/ssl-is-easy-with-traefik.html makes it out to be?

**Comment by ap** [comment]
Dupe of #254

**Comment by ap** [comment]
(The answer being yes, and the longer answer being in the other ticket. Sorry I was curt yesterday, I was in a hurry.)

**Comment by matthewpersico** [comment]
No worries.
