### ISSUE TITLE
Can't comment: getting "Publish error in template 'Comment Response': Error in tag: Can't find included template module 'HTML Head' "

### ISSUE THREAD

**Issue by choroba** [blogs-perl-org/blogs.perl.org#412]
It happens regardless of whether I'm logged in or commenting anonymously.

**Comment by ap** [comment]
Can you try again now? It seems to have been a problem only on my blog in particular. (Feel free to write just a nonsense test comment, I’ll delete it afterwards.)

**Comment by choroba** [comment]
Seems to work. Also, my original comment is now visible ;-)

**Comment by ap** [comment]
As opposed to your 27 subsequent ones, yes ;-)  I went and cleaned all that up. (Plus the several additional comments caught in the spam trap.)

Anyway – thanks for letting me know!
