### ISSUE TITLE
Request help adding a banner for The Perl and Raku Conference 2022

### ISSUE THREAD

**Issue by djzort** [blogs-perl-org/blogs.perl.org#413]
As discussed in the perl channel on TPF slack, it would be great to get a banner for this year's Perl and Raku Conference.

I can provide a banner image but I am hoping for assistance bringing it on to the bpo pages

**Comment by ap** [comment]
I’m terribly sorry that this got buried in my inbox. (I wouldn’t have minded you bugging me more about it!)

Please point me to the materials and I’ll see to getting up the promo.

**Comment by ap** [comment]
I guess this ship has sailed. 😐
