### ISSUE TITLE
Could I get an export of my posts?

### ISSUE THREAD

**Issue by oalders** [blogs-perl-org/blogs.perl.org#414]
According to https://www.movabletype.org/documentation/administrator/maintenance/import-export.html#:~:text=Movable%20Type%20import%20and%20export,blog%20system%20into%20Movable%20Type. there should be an export function, but maybe this is not available to individual users?

I could write something to do this programmatically, but if there's already a built-in way to do this, that would save me a bit of time.

**Comment by ap** [comment]
> There should be an export function, but maybe this is not available to individual users?

Correct.

> I could write something to do this programmatically, but if there's already a built-in way to do this, that would save me a bit of time.

I’ve shot you an email with the export to the address on your b.p.o user account. If that isn’t the right recipient just let me know where to send it.

**Comment by oalders** [comment]
> I’ve shot you an email with the export to the address on your b.p.o user account. If that isn’t the right recipient just let me know where to send it.

Wonderful! I got it last night and I see it's in a format which should be easy to work with. I really appreciate this and thanks for all of your hard work on the site.

**Comment by ap** [comment]
You’re welcome and gladly 🙂
