### ISSUE TITLE
https pages except for home load CSS, JavaScript over http; home page non-paging links also http-only

### ISSUE THREAD

**Issue by mjgardner** [blogs-perl-org/blogs.perl.org#415]
Modern browsers, especially the more privacy- and security-focused ones, are now preventing https pages from loading non-https resources like stylesheets and JavaScript and upgrading plain http connections to https when possible.

Although the home page seems to load CSS and scripts OK using relative links, interior pages only use plain http URLs when served over https.

Further, the links to interior pages all use http URLs even when served over https.

The net effect is that the home page looks fine, but as soon as you land on a full post (whether from home or via search), you're on an unstyled plain page.

**Comment by ap** [comment]
Thank you for taking the time to file this issue. The problems you outline are why I haven’t advertised HTTPS support anywhere yet and why #254 remains open. [The remaining work](/blogs-perl-org/blogs.perl.org/issues/254#issuecomment-1257278159) is outlined there too.
