### ISSUE TITLE
Paging broken with search?

### ISSUE THREAD

**Issue by djzort** [blogs-perl-org/blogs.perl.org#416]
Replicate the problem with the following steps:

Browse to blogs.perl.org

Under "Search blogs.perl.org" type "perlbrew"

Scroll to the bottom of the page, there will be "1 2 3 4 5 6 7 Next >"

Click 2 or any number

Error will be "414 Request-URI Too Large. Request- URI Too Large. The requested URL's length exceeds the capacity limit for this server."

**Comment by ap** [comment]
Thank you for taking the time to file an issue. This was a very long-standing issue first reported over 10 years ago in #204. I’ve now taken another look and fixed it.
