### ISSUE TITLE
CSS: Username in user profile page needs more padding against the user image. It's 0px currently.

### ISSUE THREAD

**Issue by avar** [blogs-perl-org/blogs.perl.org#54]
In Google Chrome / Firefox 3.6 on Linux [the Æ in this profile](http://blogs.perl.org/mt/mt-cp.fcgi?__mode=view&id=359) is right up against the user image.

**Comment by ap** [comment]
Doesn’t look that way for me in neither Chrome nor Firefox. I vaguely remember fixing this some time ago but I’m not sure. If you are still reproducing this in some configuration, please holler.
