### ISSUE TITLE
JS script too slow

### ISSUE THREAD

**Issue by ronsavage** [blogs-perl-org/blogs.perl.org#57]
Hi Folks

I keep getting a FF 'Unresponsive script' msg on the prettify script, saying:

Script: http://blogs.perl.org/mt/mt-static/plugins/GCPrettify/prettify.js:21

Ron Savage

**Comment by ap** [comment]
Here in 2022 this doesn’t seem to be a problem any longer. (I’ll be happy to look into it again if anyone is currently having trouble with it, though.)
