### ISSUE TITLE
Cannot find method 'datasource' for class 'MT::ObjectAsset'

### ISSUE THREAD

**Issue by avar** [blogs-perl-org/blogs.perl.org#64]
I got this error when trying to save a blog entry that I'd successfully previewed.

**Comment by ap** [comment]
I have an aversion against closing tickets unsolved but that’s will happen here. Things would be different if it were still March 2010, but here in 2023 I don’t know how I’d even go about verifying that this wasn’t already fixed while the b.p.o MT was still getting updates (up until 4.38 from 2012). 🙁
