### ISSUE TITLE
Can't print blog posts properly with Firefox

### ISSUE THREAD

**Issue by jrw** [blogs-perl-org/blogs.perl.org#66]
I know this isn't directly your issue, but printing just doesn't work.  Using Firefox 3.5.8, I see the body of the blog post show up on the second printed page (after a pretty much empty first page).  But anything that doesn't fit on that page gets cut off, even though there's a pretty much empty third page.  It would be great if I could print out a blog post with it's comments.  Thanks!

**Comment by ap** [comment]
Seems to work fine here in 2022. (Both FF and the site stylesheet have undergone some big changes since 2010.) If there is still a problem with this, feel free to holler.
