### ISSUE TITLE
Custom stylesheets for each blog

### ISSUE THREAD

**Issue by friedo** [blogs-perl-org/blogs.perl.org#72]
It would be nice if each person could upload their own stylesheet for his or her blog (not the front page) to give it some individual personality. 

I have some familiarity with MT and would be willing to help implement.

**Comment by ap** [comment]
In my view the main point of the site is really the front page. Support for individual styling of blogs means committing to at least some amount of stable interface in the markup structure, if not completely giving up control of it, so it would at least curtail my flexibility in making site-wide changes. I’ve been going in the other direction over time, reducing the ability of individual blogs to override global configuration.

Some narrowly limited customizability (like colorscheme + fonts or something) would be nice at some point, but I’m not interested in more.
