### ISSUE TITLE
Text Entered Was (still) Wrong

### ISSUE THREAD

**Issue by SueDNymme** [blogs-perl-org/blogs.perl.org#73]
I can't comment on Ovid's "Things I Can't Have" blog posting *http://blogs.perl.org/users/ovid/2010/05/things-i-cant-have.html).  Your April 26 posting indicates that the problem is fixed, but it is not.

**Comment by ap** [comment]
I’m closing because more changes happened in the long time since this was filed – but please holler if it is still an issue.
