### ISSUE TITLE
Selected text barely visible

### ISSUE THREAD

**Issue by haarg** [blogs-perl-org/blogs.perl.org#74]
When selecting text in the blog entries or content, the selection is barely visible.  The text color is changed very slightly, while the background color is changed to white, which is only visible at the very top of the page.

This is because the browser is looking at the background color to determine the selection colors.  The background color in this case is the blue from body that is seen on the sides of the page.  The white background for the text is only created with a background image.

I've only tested it in Firefox 3.6, but the following replacement CSS for #content-inner fixes this for me:
    #content-inner {
        position: relative;
        padding: 11px 20px;
        margin: 0 33px;
        background: #fff url('/static/images/bg-page-inner.png') no-repeat center top;
    }

This same issue makes the page unreadable if you have images disabled, but that's an even less important issue.

**Comment by ap** [comment]
Fixed some time ago.
