### ISSUE TITLE
Feed for tags or search results

### ISSUE THREAD

**Issue by moritz** [blogs-perl-org/blogs.perl.org#77]
I'd like to get a feed of all posts tagged with 'perl6', but it seems I can't. Whenever I search for tags, the atom feed linked in the HTML header is that of a particular user, not specific to a tag.

The same goes for search results; I'd like to have a feed for http://blogs.perl.org/mt/mt-search.fcgi?limit=20&search=perl6  (but one of them would be great already).

**Comment by ap** [comment]
You can add a `Template=feed` query parameter to a search to get its output as a news feed, i.e. (for your example)

http://blogs.perl.org/mt/mt-search.cgi?limit=20&search=perl6&Template=feed
