### ISSUE TITLE
Login fails. Submission of anonymous comment fails

### ISSUE THREAD

**Issue by ronsavage** [blogs-perl-org/blogs.perl.org#78]
Hi Folks

PITA.

The former failed with both my use.perl.ord ID which I'm sure I've used previously on blogs.perl.org, and also failed with my OpenID (from Google).

The latter failed with “Text entered was invalid”. Yeah, right!

Text follows:

> Hi Ovid
> 
> Many years ago I programmed in Snap, which is object-oriented Prolog, and that was very interesting...
> 
> But as for calling object 'experts', I disagree, although I support the thrust of your argument.
> 
> I call them 'servers', and the class is just the server factory.
> 
> The point of 'server' is that an object provides services in exactly the same way a classic server, e.g. web server, does.
> 
> And yes, we don't want to meddle with the internals of the 'server', we just want it to work, as you say.
> 
> I guess we can agree that 'expert' is more human-oriented terminology, whereas 'server' is more emphasizing the mechanistic side of things.
> 
> Cheers
> Ron Savage

**Comment by benkasminbullock** [comment]
This message is coming from the captcha:

https://github.com/movabletype/movabletype/blob/5b609af5911e6ae9ae3ceebd4acbf79cf1d2b727/lib/MT/App.pm#L2506

This is the same bug as here:

https://github.com/blogs-perl-org/blogs.perl.org/issues/67

It was supposedly fixed here:

https://github.com/blogs-perl-org/blogs.perl.org/issues/45

**Comment by ap** [comment]
This may be fixed, but there seem to have been rare reports about the issue even after the fix. I can’t tell which one this is, so I’m going to close it but, but if it is still an issue please holler.
