### ISSUE TITLE
Summary cut off and garbage inserted before the "Continue Reading" link

### ISSUE THREAD

**Issue by brianphillips** [blogs-perl-org/blogs.perl.org#82]
Somehow, the text "/var/www/index.html" is showing up right before the "Continue Reading" link on my latest blog entry.  When you click through to the actual entry, it doesn't appear, just on the front page of blogs.perl.org.  This is the entry in question: http://blogs.perl.org/users/brian_phillips/2010/06/when-rand-isnt-random.html

I don't know if it's related but the post is cut right before a single-line "block code" textile element.

**Comment by ap** [comment]
This is a duplicate of #80.
