### ISSUE TITLE
I can't log in, I can't post

### ISSUE THREAD

**Issue by trammell** [blogs-perl-org/blogs.perl.org#87]
Please delete any accounts related to me, johntrammell (at) gmail (dot) com.  I tried to create an account at one point, but the creation failed, and now I guess I have an account in an intermediate state.  I can do a password recovery, but still can't log in.

**Comment by ap** [comment]
Looks like that was done. [This account](https://blogs.perl.org/mt/mt-cp.cgi?__mode=view&id=1782) was registered in April 2012, two years after this issue was filed, and appears to be fully functional. If there’s still a problem, please holler.
