### ISSUE TITLE
Design colours unreadable on Android

### ISSUE THREAD

**Issue by peterdragon** [blogs-perl-org/blogs.perl.org#92]
The stylesheet when rendered on Webkit on Android shows normal article text as black on a dark blue background.
That makes the text almost unreadable.
E.g. http://blogs.perl.org/users/peter_edwards/2010/08/colorized-perl-code-snippets-on-ansi-terminals.html
I'm guessing the white background overlay that appears on a desktop browser isn't working on Android.

**Comment by benkasminbullock** [comment]
Safari isn't available on Android any more so this might be moot, but there is currently no problem with the site on Android from Chrome, the colours are the same as the desktop colours.

**Comment by ap** [comment]
I also changed the CSS a while ago to reduce the use of background images for the layout, which might be an explicit fix for the original could, if anyone were to go back in time and check again.

And in any case at some point the entire design will get an overhaul.

I think I’ll consider this one resolved.
