### ISSUE TITLE
Template error in RDF metadata 

### ISSUE THREAD

**Issue by dolmen** [blogs-perl-org/blogs.perl.org#97]
Have a look at the top of this page:
http://blogs.perl.org/users/graham_knop/2010/10/converting-complex-svn-repositories-to-git---part-3.html

The RDF metadata seems to be broken.

**Comment by ap** [comment]
[RDF Validator](https://www.w3.org/RDF/Validator/) finds nothing wrong with it.

**Comment by ap** [comment]
(If there is an issue somewhere feel free to holler, either here or in a new issue, even though I’ve closed this one.)
